# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AEONVCS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AEON
  pod 'Alamofire'	
  pod 'AlamofireImage'	
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SideMenu'
  pod 'DatePickerDialog'
  pod 'SwiftGifOrigin'
  pod 'ReachabilitySwift'
  pod 'SwiftWebSocket'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'PaddingLabel'
  pod 'SearchTextField'
  pod 'Starscream'
  pod 'AAViewAnimator', '1.0'
  
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'
  pod 'GrowingTextView', '0.7.2'
  #DA Stepped Progress Bar
  pod "FlexibleSteppedProgressBar"
  pod 'SwipeMenuViewController'
  pod 'SkyFloatingLabelTextField', '~> 3.0'

  pod 'IQKeyboardManagerSwift'
   pod 'Mapbox-iOS-SDK', '~> 5.7.0'  
end
